### ISSUE TITLE
Microwave and oven from ma_pops_furniture have few useful recipes - BY AndyIII

### ISSUE THREAD

**Issue by ExeVirus** [MeseCraft/MeseCraft#1]
# Original Post

Since the raw_beef and raw_chicken items are not used in Mesecraft, the usefulness of these nodes are very limited. I have a home server in which I tested adding recipes for all the fish and meat to both the microwave and oven. To the oven, I also added recipes for all flour, dough, and clay cooking. It is a convenient tool to have around. I can provide a pull request if someone points me in the right direction. I'm not sure if this should be a change to the mods that provide the cookable items, a change to ma_pops_furniture, or a new mod to add the recipes.

# First Reply - AndyIII

Here are the recipes I'm trying to add:

```
-- Extra recipes

local microwave = ma_pops_furniture.microwave
-- Recipe Registration
microwave.register_recipe("mobs:meat_raw", "mobs:meat")
microwave.register_recipe("mobs_creatures:pork_raw", "mobs_creatures:pork_cooked")
microwave.register_recipe("mobs_creatures:mutton_raw", "mobs_creatures:mutton_cooked")
microwave.register_recipe("mobs_creatures:rabbit_raw", "mobs_creatures:rabbit_cooked")
microwave.register_recipe("mobs_creatures:chicken_raw", "mobs_creatures:chicken_cooked")
microwave.register_recipe("mobs_creatures:snapper_raw", "mobs_creatures:snapper_cooked")
microwave.register_recipe("mobs_creatures:salmon_raw", "mobs_creatures:salmon_cooked")
microwave.register_recipe("mobs_creatures:clownfish_raw", "mobs_creatures:clownfish_cooked")
microwave.register_recipe("mobs_creatures:cod_raw", "mobs_creatures:cod_cooked")

local oven = ma_pops_furniture.oven
-- Recipe Registration
oven.register_recipe("mobs:meat_raw", "mobs:meat")
oven.register_recipe("mobs_creatures:pork_raw", "mobs_creatures:pork_cooked")
oven.register_recipe("mobs_creatures:mutton_raw", "mobs_creatures:mutton_cooked")
oven.register_recipe("mobs_creatures:rabbit_raw", "mobs_creatures:rabbit_cooked")
oven.register_recipe("mobs_creatures:chicken_raw", "mobs_creatures:chicken_cooked")
oven.register_recipe("mobs_creatures:snapper_raw", "mobs_creatures:snapper_cooked")
oven.register_recipe("mobs_creatures:salmon_raw", "mobs_creatures:salmon_cooked")
oven.register_recipe("mobs_creatures:clownfish_raw", "mobs_creatures:clownfish_cooked")
oven.register_recipe("mobs_creatures:cod_raw", "mobs_creatures:cod_cooked")
oven.register_recipe("farming:flour", "farming:bread")
oven.register_recipe("farming:rice_flour", "farming:rice_bread")
oven.register_recipe("farming:flour_multigrain", "farming:bread_multigrain")
oven.register_recipe("df_farming:cave_flour", "df_farming:cave_bread")
oven.register_recipe("christmas_holiday_pack:gingerbread_dough", "christmas_holiday_pack:gingerbread")
oven.register_recipe("farming:pumpkin_dough", "farming:pumpkin_bread")
oven.register_recipe("default:clay_lump", "default:clay_brick")
oven.register_recipe("default:clay", "bakedclay:natural")
```

# Second Reply - MeseCraft

Yes, the functions in these mods really need to be re-worked. its in the game because i really liked the look of the nodes adn thought they were good for home decor purposes. but we need to make them more functional. I just moved the repo today to github. but i'll try to add this this week.

**Comment by ExeVirus** [comment]
Looking at this list, I believe it'll be best to place these in `ma_pops_furniture` itself and then add dependencies to these other mods (`farming`, `mobs`, etc.), should be pretty straightforward (once I'm back with some decent internet to make a Pull Request)

**Comment by MeseCraft** [comment]
The mesecraft version of m&p furniture is significantly trimmed and edited. Also, I'm not sure those other mods would be willing to add support. But I'd be willing to continue supporting this edited version in MeseCraft, as the nodes are exceptionally nice. Adding functionality was on the eventual todo list anyways.

**Comment by AndyIII** [comment]
One nice thing about these recipes is that there isn't a need to check for the mods before adding a recipe that uses a mod item as input. The only recipe I see that needs a mod check is the bakedclay one, since the output comes from a different mod than the input.

**Comment by MeseCraft** [comment]
https://github.com/MeseCraft/MeseCraft/pull/45

**Comment by MeseCraft** [comment]
Fixed in https://github.com/MeseCraft/MeseCraft/pull/45

Thanks @AndyIII !
