### ISSUE TITLE
How to build slopes?

### ISSUE THREAD

**Issue by Mr-Andersen** [MeseCraft/MeseCraft#104]
I can't find a recipe for (any) slope on the current version of Mesecraft (I am playing on us.mese.net). Same goes for stone-cutting table.

**Comment by MeseCraft** [comment]
For some of these moreblocks shapes, you need to use the tablesaw node to access the additional shapes. A slope would be one of those. Not all materials are probably programmed to work with moreblocks more shapes correctly. Can you please review and respond if that resolves your issue?

**Comment by Mr-Andersen** [comment]
"Circular saw"! Thank you! Weird I couldn't find it before.
