### ISSUE TITLE
Error while trying to sleep in a bed

### ISSUE THREAD

**Issue by Snake161** [MeseCraft/MeseCraft#107]
Only mesecraft modpack enabled, latest version. Crash logs below

AsyncErr: Lua: Runtime error from mod '*builtin*' in callback item_OnPlace(): ...netest/games/mesecraft/mods/mesecraft_beds/functions.lua:100: bad argument #1 to 'set_physics_override' (table expected, got number)
stack traceback:
	[C]: in function 'set_physics_override'
	...netest/games/mesecraft/mods/mesecraft_beds/functions.lua:100: in function 'lay_down'
	...netest/games/mesecraft/mods/mesecraft_beds/functions.lua:171: in function 'on_rightclick'
	...rd/.minetest/games/mesecraft/mods/mesecraft_beds/api.lua:110: in function 'on_rightclick'
	/usr/share/luanti/builtin/game/item.lua:344: in function </usr/share/luanti/builtin/game/item.lua:337>

**Comment by hunt3r0one** [comment]
Duplicate of #101 sadly nothing can be done of it until #102 is accepted

**Comment by Snake161** [comment]
I see, sorry. I looked for "bed" and didn't find #101 xd

**Comment by MeseCraft** [comment]
reviewing now
