### ISSUE TITLE
Fence gates should not use "sound" key in node definition - By jwmhjwmh

### ISSUE THREAD

**Issue by ExeVirus** [MeseCraft/MeseCraft#2]
This causes an error at load time after https://github.com/minetest/minetest/commit/525fc3833c40dcca478719533a87bc7b5e285e4e.

Minetest Game seems to use the key "_gate_sound" instead now.

**Comment by ExeVirus** [comment]
I have a pull request on notabug I'll be migrating over here to address the issue.

**Comment by MeseCraft** [comment]
This was solved in a merge.
