### ISSUE TITLE
register_ore ERROR due to incorrectly set clust_scarcity

### ISSUE THREAD

**Issue by Solzdirfan** [MeseCraft/MeseCraft#34]
Line 132 of .../mods/MODULES/lootchests_modpack/lootchests/api.lua sends this error to the in-game chat upon world entry and re-entry due to clust_scarcity set as `rarity * rarity * rarity` instead of with numbers like e.g. `4 * 4 * 4`.
2022-12-26 13:04:27: ERROR[Main]: register_ore: clust_scarcity and clust_num_oresmust be greater than 0
![image](https://user-images.githubusercontent.com/121437885/209548443-26f5e6ce-e5e7-4c4b-8976-ec0b7f55f4cb.png)

**Comment by MeseCraft** [comment]
How did you find out it was the loothchests mod? This error has been bugging me for awhile. I think the API def in line 132 might be OK, but rather maybe a lootchest is not setup right. Still not sure.

**Comment by MeseCraft** [comment]
I think all the lootchests declations need to have a "    spawn_in_rarity = " to avoid this message. I'll check the chests now and see if that fixes it.

**Comment by MeseCraft** [comment]
Ah it appears to be fixed now! I adjusted the chests to have a spawn_in rarity. That seemed to fix it! I've been wanting to get rid of this one for a long time yes! Thank you!

**Comment by MeseCraft** [comment]
fix pushed into the unstable branch. Thank you!

**Comment by Solzdirfan** [comment]
I used an application called "catfish" to find what files contains `clust_scarcity` and found the file causing the error, hope this info helps for future issues.
