### ISSUE TITLE
Miner's helmet and wearable torches

### ISSUE THREAD

**Issue by AndyIII** [MeseCraft/MeseCraft#35]
I have a mod which works with wielded_light and armor to create a miner's helmet. I have a working version on the public Mesecraft Survival Server. It is craftable from 4 gold ingots, a mese crystal, and a glass block. I'm wondering how to get this mod integrated into Mesecraft. The part that makes light work for armor slots should probably be in either the wielded light mod or the armor mod, since other mods might make use of it.

The default torch doesn't allow for wielding as armor, so I made a wearable one, that can be crafted from a default torch. The torch can only take a few hits before being destroyed.

I'm unfamiliar with how to post mods on ContentDB, but I've been trying to read up on it. Any pointers would be appreciated. I also would like to be able to submit pull requests to Mesecraft itself, so guidelines in that vein would also be helpful.

**Comment by jeremyweston** [comment]
That sounds like a great idea. 
If you want, just email it to contact@mesecraft.com I can make the changes to support it in MeseCraft (will name it in a seperate mod called mesecraft_miners_helmet and include it in the repo. 
In the meantime, you should figure out how to use those services, git, contentdb. I'll be sure to include the credits for you in the mod. This is something I've wanted to have in MeseCraft for some time now actually so I'd be more than happy to include.

**Comment by AndyIII** [comment]
I sent it to that address after renaming and testing it on the public server named "Mesecraft Survival Server" (it is still loaded there if you want to see it in action). I hope I got the dependencies right and the copyright language. Thanks for the assistance. I already use git all the time at work, I just have to figure out how the Mesecraft and ContentDB submission process works.

**Comment by MeseCraft** [comment]
recieved. Thanks. 

Error:
```
ModError: Failed to load and run script from /home/jeremy/.minetest/games/MeseCraft/mods/mesecraft_miners_helmet/init.lua:
...eseCraft/mods/mesecraft_miners_helmet/wearable_torch.lua:12: attempt to index global 'wieldview' (a nil value)
stack traceback:
	...eseCraft/mods/mesecraft_miners_helmet/wearable_torch.lua:12: in main chunk
	[C]: in function 'dofile'
	...st/games/MeseCraft/mods/mesecraft_miners_helmet/init.lua:4: in main chunk
Check debug.txt for details.
```

**Comment by MeseCraft** [comment]
adding dependency "wieldview" resolved it.

**Comment by MeseCraft** [comment]
I really like the helmet. But the torch, I think I'm going to leave out.

**Comment by MeseCraft** [comment]
I just don't like how easy it is to make the torch and it seems like just having the helmet will help incitize players to make the helmet, which is a nice upgrade for mining, so it would be something to strive for as an upgrade. also, i'll likely make the armor value very low to make a trade off for armor for light, making players have to choose between light or heavier armor.

**Comment by MeseCraft** [comment]
feel free to weigh in on this.

**Comment by MeseCraft** [comment]
How are you testing on a public server? YOu can't really bring your own
mods into servers, they need to be installed server-side.

**Comment by MeseCraft** [comment]
fyi: it's installed in the game now here: https://github.com/MeseCraft/MeseCraft/tree/unstable/mods/mesecraft_miners_helmet

**Comment by MeseCraft** [comment]
I will need to push it into stable first before it reaches the main servers, that may take a bit more time as changes come in and a new stable version is published, but it will be coming soon.

**Comment by MeseCraft** [comment]
Once again, I really appreciate the contribution. Thank you! :)

**Comment by AndyIII** [comment]
If the armor set bonus bug gets fixed that would go a long way to making the tradeoff real. As it is the bonus is so miniscule that I always wear the mining helmet. The small benefit difference between a helmet and the mining helmet makes it not worth having no light. Even if the mining helmet gave 0 armor, I'd still choose it. The full-set armor bonus is currently something like 0.15% instead of 15% like the docs say.

One other note - the light doesn't work in vacuum, but that is an issue with wielded_light, not this mod. I think that mod is searching for air instead of air-like nodes. Same issue with mob spawners, really.

Having the torch gives a left-hand option for when the helmet is necessary - spacesuits, for example. However, torches shouldn't give light in drowning nodes, and would probably need to go out (i.e., become real_torch:torch). Needs some more balancing before considering introducing them.

**Comment by MeseCraft** [comment]
Basically all new changes come in through the unstable branch and work
their way up their testing, then finally into stable (main/master).

**Comment by AndyIII** [comment]
I noticed the torch images are still in the mod, but are not referenced. They can safely be removed.

**Comment by MeseCraft** [comment]
Oh ok will do asap

**Comment by MeseCraft** [comment]
Thanks andy

**Comment by hunt3r0one** [comment]
While in caves I find myself wielding the torch often rather than placing them like you would do in other games. I think this makes the early game more spooky and challenging, having the torch be your only source of light as placing it for longer periods of time would mean generating smoke & needing to be relit. I thought maybe I (or anyone else more talented) could allow the torch to be "worn" in the armor section so that its in your off-hand, and this way you can continue to mine or fight with the torch being held. I don't think this makes the game any easier as I said earlier, it creates an interesting challenge of exploring the darkness.
