### ISSUE TITLE
Reptilian elite typo causing hidden projectile

### ISSUE THREAD

**Issue by AndyIII** [MeseCraft/MeseCraft#37]
In mods/MODULES/mobs_creatures/mobs/reptilian_elite.lua on line 76, the tail image is listed as mobs_creatures_poisonball_trail.png but the texture is named mobs_creatures_**arrow**_poisonball_trail.png.

I'd like to make the pull request myself to get practice with the development process used here. I'll see what I can do just poking around, but if anyone has pointers, I'm all ears.

**Comment by MeseCraft** [comment]
Put a pr request in then but please target the unstable branch

**Comment by MeseCraft** [comment]
Thanks

**Comment by AndyIII** [comment]
Posted as #38 - not too hard. I'll look for places to do that again.
