### ISSUE TITLE
Make magic tomes a light source when held or dropped

### ISSUE THREAD

**Issue by AndyIII** [MeseCraft/MeseCraft#39]
I found this item on the todo list in MeseCraft, but I was wondering if I should put in a pull request here or [at the original source](https://github.com/mt-historical/gadgets_modpack). The source seems to be inactive, so perhaps MeseCraft owns it now.

I know a bit more about how wielded light works, so I'm in a good place to work this item. The gadget modpack whitelists its definition entries, so it isn't the one liner I was thinking initially, but I think I have a workable solution.

**Comment by MeseCraft** [comment]
Do one here please. Up to you for the other, it was an abandoned repo that only i really used until it was uploaded by mthistorical recently. Idk why they didnt credit the original dev but i think thats a bit questionable, clockgeb made these.

**Comment by AndyIII** [comment]
Thanks
