### ISSUE TITLE
I can't walk

### ISSUE THREAD

**Issue by stepanzubkov** [MeseCraft/MeseCraft#55]
When I create new world in MeseCraft, I want to walk, but `wasd` keys and arrows aren't working. In settings, there are `wasd` keys for walking. 

**Minetest version:** `5.6.1 (Linux)`
**OS:**  Arch Linux with KDE

**Screenshots:**
![Screenshot_20230326_083159](https://user-images.githubusercontent.com/83695097/227757550-f1d5ea18-6dd6-4350-a5ed-b0a63e85a666.png)

**Comment by MeseCraft** [comment]
Does it do this for Minetest game too?  Any other mods added?

**Comment by MeseCraft** [comment]
We might need log output  or  possibly a newer version of minetest for more info and testing

**Comment by stepanzubkov** [comment]
Yes, I also can't walk on Minetest game and Development test game

**Comment by MeseCraft** [comment]
Make an issue on minetest github too. I think maybe youre using touch controls or it doesnt recognize your keyboard layout? Im not certain. But it sounds like something with minetest itself.

**Comment by stepanzubkov** [comment]
Thank you. I'm using keyboard and it perfectly working in all apps and games that I use.

**Comment by stepanzubkov** [comment]
I changed walking keys to arrows and it is working! But I can't change it back to wasd

**Comment by stepanzubkov** [comment]
When I try to change it, there are empty rectangles
![Screenshot_20230326_202343](https://user-images.githubusercontent.com/83695097/227793085-f7d24c23-8264-4a76-87a5-26b0d4594621.png)

**Comment by MeseCraft** [comment]
I think the minetest engine doesnt understand your keyboard input keys right. You may have found a bug with minetest. I cant help with this. You should repot this to the minetest github for help. Copy and paste this url and show them too. Sorry!

**Comment by MeseCraft** [comment]
Im guessing youre not using a english keyboard. I think maybe the localization isnt working
