### ISSUE TITLE
Floating blocky particle-like things

### ISSUE THREAD

**Issue by eSPiYa** [MeseCraft/MeseCraft#61]
What are these blocky particle-like things that floats around? These are not solid blocks, because I can passthrough it. It moves and disappear, then re-appears.
 
![screenshot_20230527_084433](https://github.com/MeseCraft/MeseCraft/assets/5344190/86decd38-6c9b-4ee6-be93-d066c748a4c8)
![image](https://github.com/MeseCraft/MeseCraft/assets/5344190/462a9a3c-c1d5-4d59-bbb0-77f5a50e9daa)

**Comment by MeseCraft** [comment]
they're smoke

**Comment by eSPiYa** [comment]
Is this how it was intended to look like? Or there's a problem with my configuration?

> they're smoke
> […](#)
> On May 26, 2023 7:59:03 PM CDT, eSPiYa ***@***.***> wrote: What are these blocky particle-like things that floats around? These are not solid blocks, because I can passthrough it. It moves and disappear, then re-appears. ![screenshot_20230527_084433](https://github.com/MeseCraft/MeseCraft/assets/5344190/86decd38-6c9b-4ee6-be93-d066c748a4c8) ![image](https://github.com/MeseCraft/MeseCraft/assets/5344190/18375de5-fd93-41fb-a91f-b3f1a26a9b55) -- Reply to this email directly or view it on GitHub: #61 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

**Comment by MeseCraft** [comment]
It's normal to see these, but they should disappear. But sometimes when they are out of active block range, they can persist.
