### ISSUE TITLE
Crops not growing

### ISSUE THREAD

**Issue by Alatarius** [MeseCraft/MeseCraft#65]
I planted crops in one of the town's farms and after 30 game days the crops still have not grown. Unable to get food to keep health up.

**Comment by MeseCraft** [comment]
They're setup to take a long time to grow. I tried to make it take about 90 in-game days for crops to grow, as in real life, they take a season at least to get going. You can adjust this setting in the farming mod settings. 

I recommend surviving on alternative food sources until your farm is up and growing at the scale you need it to.
