### ISSUE TITLE
Not allowing to place CONTENT_IGNORE

### ISSUE THREAD

**Issue by gd2shoe** [MeseCraft/MeseCraft#77]
Running unstable branch

```
2023-10-03 11:30:57: ERROR[Server]: Not allowing to place CONTENT_IGNORE while trying to replace "mesecraft_mobs:spiderweb" at (-427,-1664,-403) (block (-27,-104,-26))

2023-10-03 11:30:58: ERROR[Server]: Not allowing to place CONTENT_IGNORE while trying to replace "air" at (-467,-1667,-436) (block (-30,-105,-28))
```

I'm seeing a lot of these.  Dozens at a time.  They pop up in chat and in the debug log.  They don't seem to impact gameplay, so far as I see.  I haven't yet had the energy to chase down the mod that's causing them.  They tend to start showing up as I approach a large cavern.  A brief Google search suggests there's probably a typo in a node name used by one of the mods.

**Comment by MeseCraft** [comment]
I can figure this one out pretty quick for you on Linux. Yes, I've seen this issue too.

with console command `grep -r "CONTENT_IGNORE"` the output is:

```
mods/MTG/tnt/init.lua:	local c_ignore = minetest.CONTENT_IGNORE
mods/MODULES/cloudlands/cloudlands.lua:local nodeId_ignore = minetest.CONTENT_IGNORE
```

**Comment by MeseCraft** [comment]
Weird, those results don't seem expected or explain this. I agree it's a bug. I used code from nssm mobs (not so simple mobs) to create the spider web shoot code. The webs get placed and replace air. I think that is what causes this. It sounds like there is some sort of node check happening when replacements are happening.
I really appreciate you raising this issue and your help. I am swamped with work.

**Comment by MeseCraft** [comment]
https://github.com/MeseCraft/MeseCraft/blob/unstable/mods/mesecraft_mobs/mobs/giant_cave_spider.lua#L137-L158

**Comment by MeseCraft** [comment]
https://github.com/MeseCraft/MeseCraft/blob/unstable/mods/mesecraft_mobs/mobs/giant_cave_spider.lua#L10-L28

**Comment by gd2shoe** [comment]
I've had a hunch for a while that it was spider related.  You're probably right.  I can't offer proof of it.
I can see errors while trying to replace unloaded nodes... but this seems to be trying to place 'ignore' nodes, quite the opposite.

**Comment by gd2shoe** [comment]
Well... It was a nice theory.
It doesn't seem to be giant_cave_spider.lua.  It also doesn't seem to be an LBM (my other guess), or an ABM, or a registered global step.  

It's _acting_ like an LBM.  What else could it be?  A node timer maybe?

**Comment by gd2shoe** [comment]
Ok.  That was a pain to find, but easy to fix.  Pull request coming soon.  (Further bug?  See below.)
When spiderwebs were moved from mobs:spiderweb to mesecraft_mobs:spiderweb, the fields liquid_alternative_flowing and liquid_alternative_source weren't updated, resulting in the engine's liquid handler trying to reference non-existent node definitions.

Now the question remains: Why was the engine trying to replace air with liquid_alternative_flowing next to a liquid source node with liquid_range = 0?  That seems likely to cause spiderwebs to just start taking over!  This may call for a faux flowing liquid that self destructs in its constructor.

**Comment by gd2shoe** [comment]
Hmm.  Can't get evidence of webs _flowing_.  I don't know what the engine is doing, but It seems correcting the liquid fields is all that's needed.
